### ISSUE TITLE
Cannot install as 'nearleyc@latest' is not in the npm registry

### ISSUE THREAD

**Issue by nwehner** [haraka/node-address-rfc2821#33]
It seems in the latest update, the NPM post-install method tries to use the module `nearleyc` which does not exist.

**Comment by nwehner** [comment]
If you try to install with NPM, this is the error output:

`npm ERR! code 1
npm ERR! path .../node_modules/address-rfc2821
npm ERR! command failed
npm ERR! command sh -c npx nearleyc <grammar.ne -o grammar.js
npm ERR! npm ERR! code E404
npm ERR! npm ERR! 404 Not Found - GET https://registry.npmjs.org/nearleyc - Not found
npm ERR! npm ERR! 404 
npm ERR! npm ERR! 404  'nearleyc@latest' is not in the npm registry.
npm ERR! npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! npm ERR! 404 
npm ERR! npm ERR! 404 Note that you can also install from a
npm ERR! npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /Users/nick/.npm/_logs/2021-01-04T22_26_49_965Z-debug.log`

**Comment by msimerson** [comment]
`nearleyc` is a binary installed by the nearley module.

```shell
➜  ~ mkdir foo
➜  ~ cd foo
➜  foo npm install nearley
npm WARN saveError ENOENT: no such file or directory, open '/Users/matt/foo/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/Users/matt/foo/package.json'
npm WARN foo No description
npm WARN foo No repository field.
npm WARN foo No README data
npm WARN foo No license field.

+ nearley@2.20.1
added 7 packages from 7 contributors and audited 7 packages in 0.446s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities

➜  foo ls -al node_modules/nearley/bin/nearley*
-rwxr-xr-x  1 matt  staff  4015 Oct 26  1985 node_modules/nearley/bin/nearley-railroad.js
-rwxr-xr-x  1 matt  staff  2408 Oct 26  1985 node_modules/nearley/bin/nearley-test.js
-rwxr-xr-x  1 matt  staff  1249 Oct 26  1985 node_modules/nearley/bin/nearley-unparse.js
-rwxr-xr-x  1 matt  staff  1368 Oct 26  1985 node_modules/nearley/bin/nearleyc.js
```
