### ISSUE TITLE
nearley output is incompatible with node.js < 11

### ISSUE THREAD

**Issue by msimerson** [haraka/node-address-rfc2821#39]
nearly produces output that uses `array.flat()` which doesn't exist in node < 11.  Nearly installs just fine, it compiles the grammar.js file, but then when Haraka calls it it crashes because `.flat` doesn't exist.

I see a couple options:

1. <b>revert the 1.x branch of this module to the pre-nearley version. Then publish this module with those changes as a 2.x branch. When Haraka drops support for node 10 in a few months, we can update to the newer major version.</b>
2. drop node.js 10.x support now.
3. add Array.prototype.flat polyfill to the grammar.js file
4. ???

**Comment by gene-hightower** [comment]
I opened an issue at https://github.com/kach/nearley/issues/564 to ask about this.

**Comment by baudehlo** [comment]
Wouldn’t a good option be to polyfill it?

**Comment by msimerson** [comment]
We could, but `flat` might not be the only call nearley generates that requires node > 10.

**Comment by msimerson** [comment]
I'm also not sure how to make sure Array gets polyfilled in every instance that might ever require address-rfc2821.  And it would still break consumers outside the Haraka ecosystem. I think reverting the 1.x branch to pre-nearley and then publishing the nearly version as 2.x, with an explicit require for node > 11, is probably the best thing.

**Comment by msimerson** [comment]
ding!💡 We could put the polyfill into the grammar.js file after nearley generates it.

**Comment by gene-hightower** [comment]
I've stared using <https://github.com/andris9/mailauth> which requires node 14.

**Comment by gene-hightower** [comment]
Is the plan for Haraka to maintain support for Node 10 until it's official end-of-life date of 2021-04-30?

**Comment by msimerson** [comment]
Our Standard Operating Procedure is to support the versions of node.js that are supported upstream. Being this close to EOL, I was feeling it was okay to drop 10.x early, but then I considered the users of this module that aren't using it in Haraka. Since this turned out to be a breaking change, it really deserved a semver major bump.

**Comment by gene-hightower** [comment]
It's worthy of a major version, I agree.
