### ISSUE TITLE
Generating parser in postinstall triggering nearley installation

### ISSUE THREAD

**Issue by moshen** [haraka/node-address-rfc2821#46]
The `postinstall` script in `package.json`:
https://github.com/haraka/node-address-rfc2821/blob/57c9347226dbd4f3b8d3d97c6651d346fb3348bc/package.json#L33

Is triggering a `nearley` package install in our systems during the bootstrap phase of our repo. I'm not exactly sure why, as the `nearley` package should already exist. This only appeared after upgrading Haraka to the latest version. For us this breaks things (probably because of locking down npm installs).

I thought I would log this as an issue as others may have run into it.

If you add the `--no-install` flag (or simply `--no` for npm >= 7, though `--no-install` still works), the local `nearley` should be used.

Alternatively, `postinstall` scripts are generally best avoided unless absolutely required. The grammar generation could be moved into a [`prepack`](https://docs.npmjs.com/cli/v9/using-npm/scripts#npm-pack:~:text=npm%20publish.-,prepack,-Runs%20BEFORE%20a) or [`pretest`](https://docs.npmjs.com/cli/v9/using-npm/scripts#npm-test) script. Looking at other examples of `nearley` it looks like it still needs to be a dependency, but generating the js at build time seems acceptable.

**Comment by msimerson** [comment]
> Alternatively, postinstall scripts are generally best avoided unless absolutely required. The grammar generation could be moved into a [prepack](https://docs.npmjs.com/cli/v9/using-npm/scripts#npm-pack:~:text=npm%20publish.-,prepack,-Runs%20BEFORE%20a) or [pretest](https://docs.npmjs.com/cli/v9/using-npm/scripts#npm-test) script. Looking at other examples of nearley it looks like it still needs to be a dependency, but generating the js at build time seems acceptable.

This is probably the best idea. I've ceased using nearly in other projects due to its lack of maintenance and inability to install in some environments.
